apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-operators
  namespace: openshift-operators
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: openshift-service-mesh
  source: redhat-operators
  sourceNamespace: openshift-marketplace