


secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the AWS Controller for Kubernetes - S3 
minioRootCreds:
  key: secret/data/global/minio_root


# Begin global parameters
