---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: system:serviceaccount:minio:default
    namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odh-cluster-role
